### ISSUE TITLE
Start device is failing

### ISSUE THREAD

**Issue by merikwesterveld** [bitrise-steplib/steps-avd-manager#16]
When starting up the avd-manager I get the following error:

Failed to run phase, error: fork/exec /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/emulator/emulator-headless: no such file or directory. 

This is de configuration (default):

- AndroidHome: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx
- APILevel: 26
- Tag: google_apis
- DeviceProfile: pixel
- CreateCommandArgs: --sdcard 512M
- StartCommandArgs: -camera-back none -camera-front none
- ID: emulator
- Abi: x86
- EmulatorChannel: 0

It just stopped working out of the blue. Is this a bug or how can I fix this?

**Comment by dweekly** [comment]
Also seeing this issue. 

https://app.bitrise.io/build/43bf990a158efe36#?tab=log

Create device
$ /opt/android-sdk-linux/tools/bin/avdmanager "--verbose" "create" "avd" "--force" "--name" "emulator" "--device" "pixel" "--package" "system-images;android-26;google_apis;x86" "--tag" "google_apis" "--abi" "x86" "--sdcard" "512M"
Start device
$ /opt/android-sdk-linux/emulator/emulator-headless "@emulator" "-verbose" "-show-kernel" "-no-audio" "-no-boot-anim" "-netdelay" "none" "-no-snapshot" "-wipe-data" "-gpu" "swiftshader_indirect" "-camera-back" "none" "-camera-front" "none"
Failed to run phase, error: fork/exec /opt/android-sdk-linux/emulator/emulator-headless: no such file or directory, output: 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | AVD Manager: Start Android Emulator (exit code: 1)            | 41.08 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-avd-manager/issues   |
| Source: https://github.com/bitrise-steplib/steps-avd-manager                 |
+---+---------------------------------------------------------------+----------+

**Comment by Roland-Bak** [comment]
Hey there, thanks for letting us know!

@merikwesterveld , could you please send us the URL to the build?
Also @merikwesterveld  and @dweekly , could you enable Support Access (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so we can take a more extensive look at the issue? :)

**Comment by lszucs** [comment]
Hi @merikwesterveld 

Please check with latest release: https://github.com/bitrise-steplib/steps-avd-manager/releases/tag/1.0.1

The issue should be fixed now. Let me know if you're facing any further issues with this.

**Comment by lszucs** [comment]
@merikwesterveld 

On a second thought, I'll close the issue for now and you may certainly reopen it, if the `1.0.1` version does not seem to work out for you! :)
