### ISSUE TITLE
AVD Manager step is failing because platform-tools/abd can't be found.

### ISSUE THREAD

**Issue by shenders13** [bitrise-steplib/steps-avd-manager#19]
Hi there,

I am trying to use the AVD Manager step. Unfortunately it is failing with the following error message:

```txt
Failed to check running devices, error: command failed, error: fork/exec /usr/local/share/android-sdk/platform-tools/adb: no such file or directory
```

Bitrise cannot find `adb`.

Here is a more detailed log:

```
Switching to workflow: run-appium-tests
INFO[21:45:36] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+

| (0) avd-manager@1                                                            |
+------------------------------------------------------------------------------+
| id: avd-manager                                                              |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-08T21:45:40Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AndroidHome: /usr/local/share/android-sdk
- APILevel: 26
- Tag: google_apis
- DeviceProfile: Nexus 5X
- CreateCommandArgs: --sdcard 512M
- StartCommandArgs: -camera-back none -camera-front none
- ID: emulator
- Abi: x86
- EmulatorChannel: 0
Failed to check running devices, error: command failed, error: fork/exec /usr/local/share/android-sdk/platform-tools/adb: no such file or directory
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | avd-manager@1 (exit code: 1)                                  | 8.56 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-avd-manager/issues   |
| Source: https://github.com/bitrise-steplib/steps-avd-manager                 |
+---+---------------------------------------------------------------+----------+
```

Locally, I have:

```bash
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

meaning that `abd` is at:

`~/Library/Android/sdk/platform-tools/adb`.

I thought that perhaps I needed to set `AndroidHome` to be `~/Library/Android/sdk` as it is on my local machine. But when I set `AndroidHome` to have the same path as set on my local machine using the Workflow Environment Variables UI, I got the same issue:

```
INFO[23:10:41] Running workflow: run-appium-tests 
Switching to workflow: run-appium-tests
INFO[23:10:42] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+

| (0) avd-manager@1                                                            |
+------------------------------------------------------------------------------+
| id: avd-manager                                                              |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-08T23:10:46Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AndroidHome: ~/Library/Android/sdk
- APILevel: 26
- Tag: google_apis
- DeviceProfile: Nexus 5X
- CreateCommandArgs: --sdcard 512M
- StartCommandArgs: -camera-back none -camera-front none
- ID: emulator
- Abi: x86
- EmulatorChannel: 0
Failed to check running devices, error: command failed, error: fork/exec ~/Library/Android/sdk/platform-tools/adb: no such file or directory
```

Notice that `AndroidHome` changed but `adb` still could not be found.

I logged the path of `abd` on the bitrise server.  I got:

```
PRINTING OUT LOCATION OF ABD:
which adb
/usr/local/bin/adb
```

This path is clearly different to both `~/Library/Android/sdk/platform-tools/adb` and `~/Library/Android/sdk/platform-tools/adb` which I suspect is why it's failing.

Please advise as to how I can run `AVD Manager` in such a way where AVD Manager knows where `adb` is.

**Comment by bitce** [comment]
Hi there!

Sorry for the inconvenience. This is due to an ongoing issue we have. In the while I'd advise to run this script before AVD:

`ln -s $ANDROID_HOME/platform-tools/platform-tools/adb $ANDROID_HOME/platform-tools/adb`

In case this doesn't work, place let us know what stack you're using to get the specific script!

**Comment by shenders13** [comment]
Hi @bitce,

Thank you for your quick reply.

As per your suggestion, I added a script prior to the AVD Manager step:

```bash
ln -s $ANDROID_HOME/platform-tools/platform-tools/adb $ANDROID_HOME/platform-tools/adb
```

Output:

```
ln -s /usr/local/share/android-sdk/platform-tools/platform-tools/adb /usr/local/share/android-sdk/platform-tools/adb
ln: /usr/local/share/android-sdk/platform-tools/adb: No such file or directory
```

**Comment by bitce** [comment]
Thanks for confirming, I was referring to the Bitrise stack that's being used. Can you paste an URL to a build where this has happened please?

**Comment by shenders13** [comment]
Oh right, please see the links below:

### Build without symlink (the initial problem)

https://app.bitrise.io/api/build/da399c9b9b54f7d7/logs.json?&download=log

### Build with symlink (as per your suggestion):

https://app.bitrise.io/build/1d54220f46736d3a#?tab=log

**Comment by bitce** [comment]
Thank you! 

Please try this script instead:

```
#!/usr/bin/env bash
# fail if any commands fails
set -e
# debug log
set -x
# write your script here
mkdir -p /usr/local/share/android-sdk/platform-tools
ln -s /usr/local/bin/adb /usr/local/share/android-sdk/platform-tools/adb 
```

**Comment by shenders13** [comment]
That did the trick 🎉 

Thanks @bitce, I'm very grateful for your time and consideration!

**Comment by shenders13** [comment]
Hi @bitce, 

4 days ago the workaround you posted [above](https://github.com/bitrise-steplib/steps-avd-manager/issues/19#issuecomment-641913311) started failing.

- July 21st https://app.bitrise.io/build/02fa701d6e59d620#?tab=log
- July 20th https://app.bitrise.io/build/1a419473ae18c0a8#?tab=log
- July 19th https://app.bitrise.io/build/45d893d08513a9e0#?tab=log
- July 18th https://app.bitrise.io/build/5b75d6fe39a40563#?tab=log

Did anything change with the `avd-manager@1` step that may account for this?

**Comment by bitce** [comment]
Hi @shenders13!

I believe what should've changed is the file locations and the workaround should no longer be necessary.

**Comment by shenders13** [comment]
Thanks @bitce, we are going to remove the workaround above this sprint. We will be in touch to let you know how it goes. Thanks again!
