### ISSUE TITLE
avd-manager@1.0 fails parsing addon-google_apis-google-21/package.xml

### ISSUE THREAD

**Issue by wkoutre** [bitrise-steplib/steps-avd-manager#25]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

avd-manager@1.0 has recently started failing; please see the log below.

The first known failure was 2021.08.11 @ 11:01 PST.

### Bitrise info

- Build URL: https://app.bitrise.io/build/60e3abb1-b149-4b93-8de5-d1e4b70a3d0f#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
INFO[18:02:04] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+

| (0) avd-manager@1.0                                                          |
+------------------------------------------------------------------------------+
| id: avd-manager                                                              |
| version: 1.0.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-08-12T18:02:09Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- AndroidHome: /usr/local/share/android-sdk
- AndroidSDKRoot: /usr/local/share/android-sdk
- APILevel: 29
- Tag: google_apis
- DeviceProfile: pixel
- CreateCommandArgs: --sdcard 512M
- StartCommandArgs: -camera-back none -camera-front none
- ID: pixel_api_29_aosp
- Abi: x86
- EmulatorChannel: 0
Initialize Android SDK
Updating emulator
$ /usr/local/share/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "--verbose" "--channel=0" "emulator"
Updating system-image packages
$ /usr/local/share/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "--verbose" "system-images;android-29;google_apis;x86"
Failed to run phase: exit status 1, output: Loading package information...                                                  
Loading local repository...                                                     
Info: Parsing /usr/local/share/android-sdk/add-ons/addon-google_apis-google-21/package.xml << ERROR
Info: Parsing /usr/local/share/android-sdk/add-ons/addon-google_apis-google-22/package.xml
Info: Parsing /usr/local/share/android-sdk/add-ons/addon-google_apis-google-23/package.xml
  </pre>
</details>

### Steps to reproduce

Setup + run the following workflow.

```
workflows:
  attach-android-emulator:
    steps:
    - avd-manager@1.0:
        inputs:
        - emulator_id: pixel_api_29_aosp
        - api_level: '29'
    description: Attach Android Emulator - Pixel API 29
    before_run: []
```

Notice that it fails.

**Comment by ofalvai** [comment]
Hey @wkoutre 👋 

We received a couple of similar reports in the past days, and after our own investigation, we think something is broken on Google's side. The `sdkmanager` command fails because the package that it tries to install depends on emulator version `30.8.2`, while the latest stable version is `30.7.5`. In fact, someone already found a bug about this here: https://issuetracker.google.com/issues/196230378

Luckily the required version is available on the canary channel, so doing an `sdkmanager --update --channel=3` should work. You can work around the issue by adding a Script step (before the AVD step) that executes this: `yes | sdkmanager --update --channel=3`

**Comment by wkoutre** [comment]
@ofalvai Hey! Thanks for such a quick response :)

This fixed the issue 💪

**Comment by ofalvai** [comment]
Looks like Google published the required version to the stable channel:

```
Available Updates:
  ID                                       | Installed | Available
  -------                                  | -------   | -------  
  emulator                                 | 30.7.5    | 30.8.4   
  system-images;android-29;google_apis;x86 | 11        | 12       
  system-images;android-30;google_apis;x86 | 9         | 10       
  ```
  
  This means that the AVD Manager step will be able to install any required emulator system image at runtime. I'm closing the issue now.

**Comment by wkoutre** [comment]
@ofalvai Unfortunately, I just tested removing the script in my `attach-avd-manager` flow and it still doesn't work.

- Failing build with script removed: https://app.bitrise.io/build/abaac241-485f-44ba-9883-a4c2c98519b3#?tab=log
- Latest successful build with script included: https://app.bitrise.io/build/20ae9c02-aefd-42ac-a8f5-34dbe7cd80dc#?tab=log
