### ISSUE TITLE
How to boot multiple emulators?

### ISSUE THREAD

**Issue by PaulWoitaschek** [bitrise-steplib/steps-avd-manager#4]
How can I boot multiple emulators and later pick in my gradle step which one I want to use for which test?

If I understand correctly, this step creates a $BITRISE_EMULATOR_SERIAL, so if I create another emulator it will overwrite the old path.

**Comment by trapacska** [comment]
Hey @PaulWoitaschek!

AFAIK: When you start a test from gradle(so you call connectedAndroidTest task), then it will test on all connected devices, and a device serial cannot be specified.(https://stackoverflow.com/questions/23960667/running-gradles-connectedandroidtest-on-a-specific-device)

If you use adb, then you can select by the `-s` flag.

Also you are right about if you use multiple `AVD Manager` step, then the output serial in the env will be overwritten: $BITRISE_EMULATOR_SERIAL.

It is not recommended to run more than one emulator in a build, the performance will be really unusable for both. Even a local PC struggles to run tasks on multiple emulators at the same time.

If you still need multiple emulators, then after the first has started, just store the actually exported env in another, like in a script step:

```
envman add --key "BITRISE_EMULATOR_SERIAL_FIRST" --value "$BITRISE_EMULATOR_SERIAL"
```

So after both started you will have $BITRISE_EMULATOR_SERIAL and $BITRISE_EMULATOR_SERIAL_FIRST as well.

Hope this helps.

Closing the issue now, as it doesn't seem to be an exact issue with the step itself. Feel free to reopen if you encounter any issues with it. Also if you have more questions about anything, please visit our http://discuss.bitrise.io site, where you can get the answers faster.

Happy Building!
🚀
