### ISSUE TITLE
Can no longer provide custom config on v1+

### ISSUE THREAD

**Issue by testifyqa** [bitrise-steplib/steps-avd-manager#42]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.*
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

In AVD Manager v0.9 and below, you are able to use custom config in case you want to change things for a base device profile, eg `hw.lcd.density` or `hw.ramSize`

From v1 and above it does not seem you can do this anymore. We have a need for this to match screen specs for a specific payment terminal we use with a  flavour of android on top. Is there a way to do this, e.g. change density height and width etc of custom config on v1 and later of AVD Manager step?

I tried manually changing the config.ini of a pixel with `sed` and then startiong up emulator from command line but got some weird error about `Qt`

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by ofalvai** [comment]
Hey @testifyqa  👋 

I think what you are looking for are the `create_command_flags` and `start_command_flags` inputs.
