### ISSUE TITLE
Add an option to change emulator channel

### ISSUE THREAD

**Issue by zawadz88** [bitrise-steplib/steps-avd-manager#8]
Hi,
Thanks for the steps you've created - it makes running instrumentation tests on Bitrise much easier :)

I was wondering if it would be possible to have an option to change the default emulator channel when downloading it with `sdkmanager`.
Currently `channel` is set to `3` (https://github.com/bitrise-steplib/steps-avd-manager/blob/master/main.go#L232) which is the Canary channel. There might be some issues with it so I think it would be good to have an option to use the stable channel instead. Maybe a chooser with [Stable/Beta/Dev/Canary](https://developer.android.com/studio/command-line/sdkmanager#options) in Step setup would be a good idea?

Is there any reason why this is set to Canary by default?

**Comment by fehersanyi-bitrise** [comment]
Hello there, really sorry for the late reply, I also seen your PR and created a card for the tooling team to check it asap.
